-- SQL Retail Sales Analysis

CREATE DATABASE sql_project_p2;

DROP DATABASE sql_project_p2;

CREATE DATABASE sql_project_p2;

-- Create Table
DROP TABLE IF EXISTS retail_sales;

CREATE TABLE retail_sales
	(
	transactions_id INT PRIMARY KEY,
    sale_date DATE,
    sale_time TIME,
    customer_id INT,
    gender VARCHAR(15),
    age INT,
    category VARCHAR(15),
    quantiy INT,
    price_per_unit FLOAT,
    cogs FLOAT,
    total_sale FLOAT
    );
    
    SELECT * FROM retail_sales
    LIMIT 10;
    
    SELECT COUNT(*) FROM retail_sales;
    
    -- Data Cleaning
    -- I noticed my table wasn't clean, so went back, cleaned the date, fill in missing values and re-imported the edited table
    
   SELECT * FROM retail_sales
   WHERE
		sale_date IS NULL
        OR
        transactions_id IS NULL
        OR 
        sale_time IS NULL
        OR 
        cogs IS NULL
   ;

ALTER TABLE retail_sales
RENAME COLUMN quantiy TO quantity;


    
    -- Data Exploration
    -- How many sales do we have?
    
    SELECT COUNT(*) as total_sale FROM retail_sales;
    
    -- How many unique customers do we have?
    
    SELECT COUNT( DISTINCT customer_id) as total_sale FROM retail_sales;
    
    -- How many unique category do we have?
    
     SELECT COUNT( DISTINCT category) as total_sale FROM retail_sales;
    
SELECT DISTINCT category FROM retail_sales;

-- Data Analysis & Business Key Problems & Answers

-- Q.1 Write a SQL query to retrieve all columns for sales made on '2022-11-05'
-- Q.2 Write a SQL query to retrieve all transactions where the category is 'Clothing' and the quantity sold is more than 4 in the month of Nov-2022
-- Q.3 Write a SQL query to calculate the total sales (total_sale) for each category.
-- Q.4 Write a SQL query to find the average age of customers who purchased items from the "Beauty' category.
-- Q.5 Write a SQL query to find all transactions where the total_sale is greater than 1000.
-- Q.6 Write a SQL query to find the total number of transactions (transaction_id) made by each gender in each category.
-- Q.7 Write a SQL query to calculate the average sale for each month. Find out best selling month in each year.
-- Q.8 Write a SQL query to find the top 5 customers based on the highest total sales.
-- Q.9 Write a SQL query to find the number of unique customers who purchased items from each category.
-- Q.10 Write a SQL query to find the total revenue generated by each gender.
-- Q.12 Write a SQL query to find customers who have made more than 3 transactions.
-- Q.13 Write a SQL query to find the percentage contribution of each category to the total revenue.
-- Q.14 Write a SQL query to retrieve the most recent transaction for each customer.
-- Q.15 Write a SQL query to find customers who have purchased from more than one category.
-- Q.16 Write a SQL query to find the month with the highest number of transactions for each category.
-- Q.17 Write a SQL query to rank customers based on their total spending using a window function.
-- Q.18 Write a SQL query to calculate a running total of sales ordered by date.
-- Q.19 Write a SQL query to find the average transaction value per age group (e.g. 18-25, 26-35, 36-50, 51+).
-- Q.20 Write a SQL query to identify customers who haven't made a purchase in the last 3 months of the dataset.


-- Q.1 Write a SQL query to retrieve all columns for sales made on '2022-11-05'
SELECT *
FROM retail_sales
WHERE sale_date = '2022-11-05';

-- Q.2 Write a SQL query to retrieve all transactions where the category is 'Clothing' and the quantity sold is more than 4 in the month of Nov-2022

SELECT * 
FROM retail_sales
WHERE category = 'Clothing'
AND 
	DATE_FORMAT(sale_date, '%Y-%m') = '2022-11'
	AND quantity >= 4;


-- Q.3 Write a SQL query to calculate the total sales (total_sale) for each category.

 SELECT category,
	SUM(total_sale) AS Sum_of_Sale
	FROM retail_sales
	GROUP BY category;
    
    -- Q.4 Write a SQL query to find the average age of customers who purchased items from the "Beauty' category.
    
    SELECT
		ROUND(AVG(age), 2) AS avg_age
		FROM retail_sales
		WHERE category = 'Beauty';
    
    -- Q.5 Write a SQL query to find all transactions where the total_sale is greater than 1000.
    
    SELECT * 
    FROM retail_sales
    WHERE total_sale > 1000;
    
    -- Q.6 Write a SQL query to find the total number of transactions (transaction_id) made by each gender in each category.
    
    SELECT category, gender, 
    COUNT(*) as total_transaction
    FROM retail_sales
    GROUP BY gender, category
    ORDER BY category;
    
    -- Q.7 Write a SQL query to calculate the average sale for each month. Find out best selling month in each year.
    
    SELECT * FROM
    (
		SELECT
			YEAR(sale_date)as year,
			MONTH(sale_date) as month,
			AVG(total_sale),
			RANK() OVER(PARTITION BY YEAR(sale_date) ORDER BY AVG(total_sale) DESC) AS ranking
        FROM retail_sales
        GROUP BY year, month
	) AS t1
    WHERE ranking = 1;
    
    -- Q.8 Write a SQL query to find the top 5 customers based on the highest total sales.
    
    SELECT customer_id,
    SUM(total_sale) AS total_sales
     FROM retail_sales
     GROUP BY customer_id
    ORDER BY total_sales DESC
    LIMIT 5;
     

   --  Q.9 Write a SQL query to find the number of unique customers who purchased items from each category. 

 SELECT category,
	COUNT(DISTINCT customer_id)
     FROM retail_sales
     GROUP BY category;
  
    -- Q.10 Write a SQL query to find the total revenue generated by each gender

SELECT gender,
    SUM(total_sale) AS total_revenue
FROM retail_sales
GROUP BY gender;

-- Q.11 Write a SQL query to find the best selling category by total revenue in each month.



SELECT *
FROM 
(
SELECT 
	DATE_FORMAT(sale_date, '%Y-%m') AS month,
    category,
    SUM(total_sale) AS total_revenue,
    RANK() OVER(PARTITION BY DATE_FORMAT(sale_date, '%Y-%m')
    ORDER BY SUM(total_sale) DESC) AS ranking
FROM retail_sales
GROUP BY DATE_FORMAT(sale_date, '%Y-%m'), category
)AS monthly_sales
WHERE ranking =1;


-- Q.12 Write a SQL query to find customers who have made more than 3 transactions.


SELECT customer_id, COUNT(transactions_id) AS total_count
FROM retail_sales
GROUP BY customer_id
HAVING COUNT(transactions_id) > 3;


-- Q.13 Write a SQL query to find the percentage contribution of each category to the total revenue.


SELECT category,
SUM(total_sale) AS sum_total,
SUM(total_sale)/ (SELECT SUM(total_sale) FROM retail_sales) * 100 AS Percentage
FROM retail_sales
GROUP BY category;


-- Q.14 Write a SQL query to retrieve the most recent transaction for each customer.


SELECT 
    customer_id,
    MAX(sale_date) AS most_recent_transaction
FROM retail_sales
GROUP BY customer_id;


-- Q.15 Write a SQL query to find customers who have purchased from more than one category.

SELECT customer_id,
	COUNT(DISTINCT category)
     FROM retail_sales
     GROUP BY customer_id
     HAVING COUNT(DISTINCT category) > 1;


 -- Q.16 Write a SQL query to find the month with the highest number of transactions for each category.


SELECT * FROM (
    SELECT 
        DATE_FORMAT(sale_date, '%Y-%m') AS month,
        category,
        COUNT(transactions_id) AS total_transactions,
        RANK() OVER(PARTITION BY category ORDER BY COUNT(transactions_id) DESC) AS ranking
    FROM retail_sales
    GROUP BY DATE_FORMAT(sale_date, '%Y-%m'), category
) AS highest_transactions
WHERE ranking = 1;

-- Q.17 Write a SQL query to rank customers based on their total spending using a window function.

SELECT customer_id,
    SUM(total_sale) AS total_spending,
    RANK() OVER(ORDER BY SUM(total_sale) DESC) AS ranking
FROM retail_sales
GROUP BY customer_id;


-- Q.18 Write a SQL query to calculate a running total of sales ordered by date.

SELECT sale_date,
    SUM(total_sale) AS daily_sale,
    SUM(SUM(total_sale)) OVER(ORDER BY sale_date) AS running_total
FROM retail_sales
GROUP BY sale_date;


-- Q.19 Write a SQL query to find the average transaction value per age group (e.g. 18-25, 26-35, 36-50, 51+)

SELECT 
    CASE
        WHEN age BETWEEN 18 AND 25 THEN '18-25'
        WHEN age BETWEEN 26 AND 35 THEN '26-35'
        WHEN age BETWEEN 36 AND 50 THEN '36-50'
        ELSE '51+'
    END AS age_group,
    ROUND(AVG(total_sale), 2) AS avg_transaction
FROM retail_sales
GROUP BY age_group;


-- Q.20 Write a SQL query to identify customers who haven't made a purchase in the last 3 months of the dataset.       

SELECT DISTINCT customer_id
FROM retail_sales
WHERE customer_id NOT IN (
    SELECT DISTINCT customer_id
    FROM retail_sales
    WHERE sale_date >= DATE_SUB((SELECT MAX(sale_date) FROM retail_sales), INTERVAL 3 MONTH)
);


-- End of Project